name: HacktoberSentinel Self-Test

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run HacktoberSentinel
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          close-spam: 'false'
